torchrun --nnodes=1 --nproc_per_node=1 run_topk_module_analysis.py \
    --input_model meta-llama/Llama-3.2-3B \
    --w_bits 4 \
    --a_bits 4 \
    --k_bits 4 \
    --v_bits 4 \
    --nb_eval_runs 1 \
    --nsamples 256 \
    --do_train False \
    --do_eval True \
    --per_device_eval_batch_size 4 \
    --model_max_length 2048 \
    --fp16 False \
    --bf16 True \
    --save_safetensors False \
    --w_clip --a_asym --k_asym --v_asym --k_groupsize 128 --v_groupsize 128 \
    --rotate \
    --top_k 10 \
    --beta 0.5 \
    --load_qmodel_path "quantized_weights_offline_rotated_llama-3.2-3b.pt"